# Generated by Django 3.1.1 on 2021-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
